[package]
name = "trillium-example-app"
version = "0.1.0"
edition = "2018"

[dependencies]
trillium = "1.4"
trillium-compression = "0.3"
trillium-conn-id = "0.3"
trillium-cookies = "0.5"
trillium-head = "0.3"
trillium-logger = "0.5"
trillium-method-override = "0.3"
trillium-router = "0.5"
trillium-smol = "0.7"

[dev-dependencies]
trillium-testing = { version = "0.10", features = ["smol"] }
